POST http://localhost:8888/api/v1/wallet/post/walletype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json

{
    "code":"ETH",
    "name":"Ethereum"
}
#####
GET http://localhost:8888/api/v1/wallet/get/walletype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json
###
POST http://localhost:8888/api/v1/transaction/post/transactionType
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json

{
    "typeName":"Chuyển tiền",
    "type":"send"
}
###
PUT http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmVjNGM2ZGI5NDFjOWIwMmMzN2RiYiIsImlhdCI6MTcxODUzNTM2Nn0.7iHRTDvTe6kiSZduP3nD-l4v9aR_m5V9At59z37Jy6I
Content-Type: application/json

{
    "receiver":"666db27d249d2a464f324773",
    "amount":"10",
    "wallet_type":"VND",
    "transaction_type":"send",
    "message":"Em dep lam"
}
###
PUT http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json

{
    "receiver":"666ec4c6db941c9b02c37dbb",
    "amount":"10",
    "wallet_type":"VND",
    "transaction_type":"send",
    "message":"Em dep lam"
}

###
GET http://localhost:8888/api/v1/transaction/get/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json
###
GET http://localhost:8888/api/v1/transaction/get/transactions-send
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json
###
GET http://localhost:8888/api/v1/transaction/get/transactions-receive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json

###
POST http://localhost:8888/api/v1/wallet/post/wallet-eth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmVjNGM2ZGI5NDFjOWIwMmMzN2RiYiIsImlhdCI6MTcxODUzNTM2Nn0.7iHRTDvTe6kiSZduP3nD-l4v9aR_m5V9At59z37Jy6I
Content-Type: application/json

###
##eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmZmZGQ0MDkzZTZiM2E4NDFiMjY0MyIsImlhdCI6MTcxODYxNTUwOH0.QhwBNIp9DE2V3ucekZQNXPhaO11b8y7kjwWrSxdYZHU
POST http://localhost:8888/api/v1/wallet/get/address-eth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmVjNGM2ZGI5NDFjOWIwMmMzN2RiYiIsImlhdCI6MTcxODUzNTM2Nn0.7iHRTDvTe6kiSZduP3nD-l4v9aR_m5V9At59z37Jy6I
Content-Type: application/json

POST http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json

{
    "receiver":"666ec4c6db941c9b02c37dbb",
    "amount":"10",
    "wallet_type":"VND",
    "type":"send",
    "message":"Em dep lam"
}
###

POST http://localhost:8888/api/v1/wallet/post/currency
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json

{
    "symbol":"ETH",
    "name":"Ethereum",
    "image":""
}

###
POST http://localhost:8888/api/v1/partner/signup
Content-Type: application/json

{
    "email":"partner@gmail.com",
    "password":"123123123"
}
####

POST http://localhost:8888/api/v1/partner/verify
Content-Type: application/json

{
    "email":"partner@gmail.com",
    "otp":"577735"
}
###
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2E2ZTlkN2Y4Y2Q3MjhjNjYxYTQyMSIsImlhdCI6MTcxOTI5OTc0MX0.9VjD_O6b4HWlvC34sC80DTzqRLDeZYAOFk_tXa96Zuw


### 
POST http://localhost:8888/api/v1/user/signup
Content-Type: application/json

{
    "email":"nguyn10@presspay.com",
    "password":"nguyn123"
}
###
POST http://localhost:8888/api/v1/user/signup/verify
Content-Type: application/json

{
    "email":"nguyn10@presspay.com",
    "otp":"507493"
}
###
POST http://localhost:8888/api/v1/user/signin
Content-Type: application/json

{
    "email":"nguyn10@presspay.com",
    "password":"nguyn123"
}
###
POST http://localhost:8888/api/v1/user/signin/verify
Content-Type: application/json

{
    "email":"nguyn10@presspay.com",
    "otp":"981476"
}
###
POST http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

{
    "receiver":"667ec4cd43fb999edadf1691",
    "amount":"12.1",
    "currency":"VND",
    "message":"Em dep lam, lam ny a nha"
}

###
PUT http://localhost:8888/api/v1/wallet/send-money/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

{
    "security_code":"123123",
    "transactionID":"667ef0446f8ed5c93fc28a7d",
    "currency":"VND",
    "amount":"12.1",
    "sender":"667eec814a9447549addf0d6",
    "receiver":"667ec4cd43fb999edadf1691"
}
###
GET http://localhost:8888/api/v1/wallet/get-wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json
###
PUT http://localhost:8888/api/v1/user/update/update-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

{
    "full_name":"Tony Lee"
}
###
PUT http://localhost:8888/api/v1/user/update-security-code
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

{
    "security_code":"456456"
}

###
POST http://localhost:8888/api/v1/wallet/deposit-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

{
    "currency":"USD",
    "amount":"1000",
    "cardID":"667ff65937882ad34117224e"
}


###
POST http://localhost:8888/api/v1/wallet/deposit-money/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

{
    "security_code":"456456",
    "amount":"1000",
    "currency":"USD",
    "transactionID":"66800737b3e2d7800a88ed85"
}

###
POST http://localhost:8888/api/v1/card/addcard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

{
    "name":"NGUYEN VAN A",
    "number":"4242424242442",
    "cvv":"123",
    "expiryMonth":"12",
    "expiryYear":"2024"
}

###
GET	http://localhost:8888/api/v1/card/getcards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

###
GET	http://localhost:8888/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json


### 
GET http://localhost:8888/api/v1/transaction/get/transaction/details/667eefc0afb73ef557582259
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json

### 
GET http://localhost:8888/api/v1/transaction/get/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VlYzgxNGE5NDQ3NTQ5YWRkZjBkNiIsImlhdCI6MTcxOTU5NDExM30.xBtP_vvMTB5_l9WoNcKG1wKhFA7LnNTgjcIwIAJ7XmU
Content-Type: application/json



###Partner
PUT http://localhost:8888/api/v1/transaction/get/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ODM4MWRiMGNmYzJkZWI2Mzc5ZmVkYSIsImlhdCI6MTcxOTg5NDQ5Mn0.jQlG3E0vNvF25NaIQjZXkEbHibbSUEm29OMBtE-r1Ws
Content-Type: application/json