POST http://localhost:8888/api/v1/wallet/post/walletype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json

{
    "code":"ETH",
    "name":"Ethereum"
}
#####
GET http://localhost:8888/api/v1/wallet/get/walletype
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json
###
POST http://localhost:8888/api/v1/transaction/post/transactionType
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json

{
    "typeName":"Chuyển tiền",
    "type":"send"
}
###
PUT http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmVjNGM2ZGI5NDFjOWIwMmMzN2RiYiIsImlhdCI6MTcxODUzNTM2Nn0.7iHRTDvTe6kiSZduP3nD-l4v9aR_m5V9At59z37Jy6I
Content-Type: application/json

{
    "receiver":"666db27d249d2a464f324773",
    "amount":"10",
    "wallet_type":"VND",
    "transaction_type":"send",
    "message":"Em dep lam"
}
###
PUT http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json

{
    "receiver":"666ec4c6db941c9b02c37dbb",
    "amount":"10",
    "wallet_type":"VND",
    "transaction_type":"send",
    "message":"Em dep lam"
}

###
GET http://localhost:8888/api/v1/transaction/get/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json
###
GET http://localhost:8888/api/v1/transaction/get/transactions-send
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json
###
GET http://localhost:8888/api/v1/transaction/get/transactions-receive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json

###
POST http://localhost:8888/api/v1/wallet/post/wallet-eth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmVjNGM2ZGI5NDFjOWIwMmMzN2RiYiIsImlhdCI6MTcxODUzNTM2Nn0.7iHRTDvTe6kiSZduP3nD-l4v9aR_m5V9At59z37Jy6I
Content-Type: application/json

###
##eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmZmZGQ0MDkzZTZiM2E4NDFiMjY0MyIsImlhdCI6MTcxODYxNTUwOH0.QhwBNIp9DE2V3ucekZQNXPhaO11b8y7kjwWrSxdYZHU
POST http://localhost:8888/api/v1/wallet/get/address-eth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmVjNGM2ZGI5NDFjOWIwMmMzN2RiYiIsImlhdCI6MTcxODUzNTM2Nn0.7iHRTDvTe6kiSZduP3nD-l4v9aR_m5V9At59z37Jy6I
Content-Type: application/json

POST http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODU1NjE4NH0.HcJ4CH0F6Wf_Ri5v3LpAT7W5TwQV6a0oS0Vv2qPHYgc
Content-Type: application/json

{
    "receiver":"666ec4c6db941c9b02c37dbb",
    "amount":"10",
    "wallet_type":"VND",
    "type":"send",
    "message":"Em dep lam"
}
###

POST http://localhost:8888/api/v1/wallet/post/currency
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmRiMjdkMjQ5ZDJhNDY0ZjMyNDc3MyIsImlhdCI6MTcxODQ2NTE0OX0.r61EHZYDDA26EMC-3YJtlHyvUZe3yy1Y5Es6ZjofoXw
Content-Type: application/json

{
    "_id":"ETH",
    "symbol":"ETH",
    "name":"Ethereum"
}

###
POST http://localhost:8888/api/v1/partner/signup
Content-Type: application/json

{
    "email":"nguynthuhigh1@gmail.com",
    "password":"123123123"
}
####

POST http://localhost:8888/api/v1/partner/verify
Content-Type: application/json

{
    "email":"nguynthuhigh1@gmail.com",
    "otp":"472726"
}
###
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2E2ZTlkN2Y4Y2Q3MjhjNjYxYTQyMSIsImlhdCI6MTcxOTI5OTc0MX0.9VjD_O6b4HWlvC34sC80DTzqRLDeZYAOFk_tXa96Zuw


### 
POST http://localhost:8888/api/v1/user/signup
Content-Type: application/json

{
    "email":"user_test02@presspay.com",
    "password":"nguyn123"
}
###
POST http://localhost:8888/api/v1/user/signup/verify
Content-Type: application/json

{
    "email":"user_test02@presspay.com",
    "otp":"154159"
}

###
POST http://localhost:8888/api/v1/wallet/send-money
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VjM2ZjYzk0YTRhMDdkNTFlYTMwMSIsImlhdCI6MTcxOTU4Mzc0MH0.oy8SXcQA03KpwBHdyqnofz0bPU9XmruVrMqM4zL5vnM
Content-Type: application/json

{
    "receiver":"667ec4cd43fb999edadf1691",
    "amount":"12.1",
    "currency":"USD",
    "message":"Em dep lam, lam ny a nha"
}

###
PUT http://localhost:8888/api/v1/wallet/send-money/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2N2VjM2ZjYzk0YTRhMDdkNTFlYTMwMSIsImlhdCI6MTcxOTU4Mzc0MH0.oy8SXcQA03KpwBHdyqnofz0bPU9XmruVrMqM4zL5vnM
Content-Type: application/json

{
    "security_code":"123123",
    "transactionID":"667edb77b74fa293c2842ae5",
    "currency":"USD",
    "amount":"12.1",
    "sender":"667ec3fcc94a4a07d51ea301",
    "receiver":"667ec4cd43fb999edadf1691"
}